### ISSUE TITLE
Can't get CNN_final_model_weights.h5 file

### ISSUE THREAD

**Issue by jamesrgraham** [zhenglz/onionnet#5]
Hello,

When I try to download the git repo, I get this error:

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/zhenglz/onionnet.git/info/lfs'

I think I can get everything except for CNN_final_model_weights.h5.

Is there another place to get this file?

Thanks!

**Comment by jamesrgraham** [comment]
Never mind, I just saw the other posted solution. Thanks!

**Comment by zhenglz** [comment]
I am glad that you have found a solution.
