### ISSUE TITLE
Question about equation of `pK_a`

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [zhenglz/onionnet#7]
In the paper, you define `pK_a` as follows:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/28868457/96765866-d7f12400-140c-11eb-8797-276233dc9fd5.png">
Does that means you transform `K_i`, `K_d` and `IC50` into negative log and **consider they are the same**?
For example, If one compound-protein pair has `K_i` = 1 nM and another compound-protein pair has `K_d` = 1 nM. Then in your dataset, they have the same `pK_a` value? 
Is that a correct way to transform different metrics?
Thank you very much!

**Comment by zhenglz** [comment]
"Does that means you transform K_i, K_d and IC50 into negative log and consider they are the same?"
In this project, yes. We treated all measures the same way. However, we should be careful, it is commonly accepted that we could treat Ki and Kd the same, but IC50 should be treated separately. Generally Ki and IC50 could be somehow correlated, to  have more samples, we transformed the measures all using the above equation. 

"For example, If one compound-protein pair has K_i = 1 nM and another compound-protein pair has K_d = 1 nM. Then in your dataset, they have the same pK_a value?" Yes. 

Theoretically, the IC50 should not mix with Ki and Kd, but there is a theory (Cheng-Prusoff equation) to convert Ki and Kd to IC50. 

Please refer to this paper:

Newton, P., Harrison, P., & Clulow, S. (2008). A novel method for determination of the affinity of protein: protein interactions in homogeneous assays. Journal of biomolecular screening, 13(7), 674-682.
