### ISSUE TITLE
Question about feature generation

### ISSUE THREAD

**Issue by agave233** [zhenglz/onionnet#8]
Hi,
Thanks for your great work! I have tried generating features in two different ways. The first way is running the code generate_features.py in this repo, which takes the complex pdb file as input, and the other way is running the code gen_features.py in another repo (https://github.com/zhenglz/onionnet_featurize) you mentioned in README. But I find the generated features are different for the same pdb code. Could you please explain it or tell me which is right?

Thanks!

**Comment by zhenglz** [comment]
The difference is from the way of contacts cutoff setting.

In this repo, the lowest cutoff is 1.0 Angstrom (0.1 nanometer)

```
n_cutoffs = np.linspace(0.1, 3.1, n_shells)
```

Whereas in the other repo (onionnet_featurize) the lowest cutoff is set as 0.5 Angstrom.

```
parser.add_argument("-upbound", type=float, default=31.0,
                    help="Input, optional. Default is 3.1 nm. "
                         "The largest distance cutoff.")
parser.add_argument("-lowbound", type=float, default=0.5,
                    help="Input, optional. Default is 0.05 nm. "
                         "The lowest distance cutoff.")
```

If you are using the repo "onionnet_featurize", please add an argument "-lowbound 1.0" in the command line for featurization and compare the features again. 

Thanks!

**Comment by agave233** [comment]
> The difference is from the way of contacts cutoff setting.
> 
> In this repo, the lowest cutoff is 1.0 Angstrom (0.1 nanometer)
> 
> ```
> n_cutoffs = np.linspace(0.1, 3.1, n_shells)
> ```
> 
> Whereas in the other repo (onionnet_featurize) the lowest cutoff is set as 0.5 Angstrom.
> 
> ```
> parser.add_argument("-upbound", type=float, default=31.0,
>                     help="Input, optional. Default is 3.1 nm. "
>                          "The largest distance cutoff.")
> parser.add_argument("-lowbound", type=float, default=0.5,
>                     help="Input, optional. Default is 0.05 nm. "
>                          "The lowest distance cutoff.")
> ```
> 
> If you are using the repo "onionnet_featurize", please add an argument "-lowbound 1.0" in the command line for featurization and compare the features again.
> 
> Thanks!

Thanks a lot! I changed the low-bound and reran the codes, but I found the results are still different from the dataset you provided (the file features_testing_v2016core_290_pka.csv). I think the reason might be the raw data is different. To keep the data consistent, could you please share the csv-format training dataset with features similar to features_testing_v2016core_290_pka.csv?

**Comment by zhenglz** [comment]
Ok, please provide your email address in private mail thus I could send you the google link for the features.

**Comment by agave233** [comment]
> Ok, please provide your email address in private mail thus I could send you the google link for the features.

Please send to this email: lishuangli0209@gmail.com. Thanks!
